---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "RTP Big Data Analytics for Cyber Security"
keywords:    "security meetup, security, cyber security, cyber security conference, raleigh, north carolina, research triangle park, rtp, big data, big data analytics, analytics, math, data science, data scientist, hacking, hackers, hacker"
description: "RTP Big Data Analytics for Cyber Security"
source_link: "https://github.com/RTP-Big-Data-Cyber-Security/RTP-Big-Data-Cyber-Security.github.io"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#FFFFFF'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  darkRed:   '#941212'
  yellow:    '#FFFFCC'
  darky:     '#000066'
